### ISSUE TITLE
A race condition?

### ISSUE THREAD

**Issue by piotrmaslanka** [smok-serwis/coolamqp#15]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/thread.py", line 27, in run
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/epoll_listener.py", line 86, in wait
    sock.on_read()
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/socket.py", line 98, in on_read
    self.my_on_read(data)
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py", line 60, in put
    while self._statemachine():
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py", line 140, in _statemachine
    self.on_frame(frame)
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/connection.py", line 217, in on_frame
    watch_triggered = watch.is_triggered_by(frame)
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/watches.py", line 126, in is_triggered_by
    self.callable(frame.payload)
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 234, in on_delivery
    self.receiver.on_basic_deliver(sth)
AttributeError: 'NoneType' object has no attribute 'on_basic_deliver'

**Comment by piotrmaslanka** [comment]
Needs more data. Waiting for it to happen again.
