### ISSUE TITLE
A battlefield report

### ISSUE THREAD

**Issue by piotrmaslanka** [smok-serwis/coolamqp#40]
```
Usługa zgłaszająca: svcr@dev8
Wersja smok4/core: 4.5.27
Czas zgłoszenia: 2019-12-25 01:17:55 czasu lokalnego
SMOK4_SLOT=8
SMOK4_SERVICE=svcr
Etykieta zdarzenia: handler.failed
Klasa zdarzenia: develop/fail

trigger : HandlerStopOrder(device_id='101187585uart')

trackback : Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/__init__.py", line 69, in handle_msg
    self.inner_handle_msg(msg, msgtype)
  File "/usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/__init__.py", line 96, in inner_handle_msg
    self.__intercept_unload(msg.device_id, None, None, None)
  File "/usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/__init__.py", line 251, in __intercept_unload
    self.vport_data_mapper.device_shutdown(device_id)
  File "/usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/trackers.py", line 131, in device_shutdown
    self.conmap[(k[0], k[1], device_id)].cancel()
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 191, in cancel
    self.on_close)
  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/channeler.py", line 197, in method_and_watch
    assert self.channel_id is not None
AssertionError

* Stack trace, innermost first
** method_and_watch at /usr/local/lib/python2.7/dist-packages/coolamqp/attaches/channeler.py:197
*** callable: <bound method Consumer.on_close of <coolamqp.attaches.consumer.Consumer object at 0x7f89b4403890>>
*** self: <coolamqp.attaches.consumer.Consumer object at 0x7f89b4403890>
*** method_classes_to_watch: [<class 'coolamqp.framing.definitions.BasicCancelOk'>]
*** method_payload: BasicCancel('12f688eb37c9477ab003307dc35750ea', False)
** cancel at /usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py:191
*** self: <coolamqp.attaches.consumer.Consumer object at 0x7f89b4403890>
** device_shutdown at /usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/trackers.py:131
*** x: {(119275521, 0): ('119275521uart', <function wrap_data_handler at 0x7f89b4469848>), (109641729, 1): ('109641729gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89b4032250>>), (105185281, 1): ('105185281gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c049cbd0>>), (112984065, 0): ('112984065uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89c04a16d0>>), (109314049, 1): ('109314049gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89944bae10>>), (101187585, 0): ('101187585uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b44ba550>>), (100073473, 0): ('100073473uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b44df450>>), (114884609, 0): ('114884609', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b42def50>>), (113049601, 2): ('113049601at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b4522210>>), (13959169, 1): ('13959169gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89b4076b10>>), (109051905, 0): ('109051905uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b4060590>>), (105185281, 2): ('105185281at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89c047e3d0>>), (113836033, 1): ('113836033gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c052a810>>), (121438209, 0): ('121438209uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f8994455b10>>), (101974017, 1): ('101974017gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89b43b6910>>), (123207681, 0): ('114556929uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b42decd0>>), (103677953, 1): ('103677953gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c0518510>>), (109707265, 1): ('109707265gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89b4047a90>>), (106823681, 2): ('106823681at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89c0523a10>>), (101580801, 2): ('101580801at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b43af250>>), (118947841, 2): ('118947841at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b45146d0>>), (107806721, 2): ('107806721at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b40787d0>>), (107282433, 1): ('107282433gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c049b8d0>>), (118489089, 0): ('118489089uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89c0491f50>>), (720897, 1): ('1', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b4403b90>>), (15007745, 1): ('15007745gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f899447b410>>), (105709569, 0): ('105709569uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89c0518150>>), (102563841, 2): ('102563841at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b45287d0>>), (103677953, 2): ('103677953at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89c04b86d0>>), (15925249, 0): ('15925249', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f899447b510>>), (113836033, 0): ('113836033uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89c0491110>>), (108331009, 0): ('108331009uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b409b6d0>>), (101449729, 0): ('101449729uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b43ae050>>), (102957057, 1): ('102957057gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c05232d0>>), (104529921, 1): ('104529921gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c04d5890>>), (101777409, 1): ('101777409gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89b43e2a50>>), (15597569, 2): ('15597569at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89944e4dd0>>), (123207681, 1): ('114556929gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c0519f50>>), (105644033, 0): ('105644033uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89c04f3950>>), (119275521, 2): ('119275521at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89944d9590>>), (108331009, 1): ('108331009gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89b408bc90>>), (119013377, 2): ('119013377at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b40a3f90>>), (109641729, 2): ('109641729at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b4047f90>>), (111673345, 2): ('111673345at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89b44c68d0>>), (14811137, 1): ('14811137gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89c0519850>>), (10878977, 1): ('10878977', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b40a1d50>>), (109314049, 0): ('109314049uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89944c7150>>), (15007745, 2): ('15007745at', <bound method SVCRHandler.on_sssp_data of <svcr.apps.csqtrack.SVCRHandler object at 0x7f89944c74d0>>), (101318657, 0): ('101318657uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b43ba290>>), (120848385, 1): ('120848385gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89b4085290>>), (119341057, 1): ('119341057gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f89944ea3d0>>), (121438209, 1): ('121438209gpio', <bound method SVCRHandler.on_sssp_data of <svcr.apps.gpio.SVCRHandler object at 0x7f899449ed50>>)}
*** k: (101187585, 0)
*** device_id: '101187585uart'
*** self: <svcr.worker.eventloop.trackers.VportDataMapper object at 0x7f89b81b0150>
*** v: ('101187585uart', <bound method SVCRHandler.on_sssp_data of <svcr.apps.semanta.SVCRHandler object at 0x7f89b44ba550>>)
** __intercept_unload at /usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/__init__.py:251
*** exception: None
*** report_to_catalog: False
*** self: <EventLoop(eventloop, started 140229448578816)>
*** trigger: None
*** trackback: None
*** device_id: '101187585uart'
** inner_handle_msg at /usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/__init__.py:96
*** msg: HandlerStopOrder(device_id='101187585uart')
*** self: <EventLoop(eventloop, started 140229448578816)>
*** msgtype: <class 'svcr.worker.eventloop.tqmifc.HandlerStopOrder'>
** handle_msg at /usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/__init__.py:86
*** e: AssertionError()
*** self: <EventLoop(eventloop, started 140229448578816)>
*** msgtype: <class 'svcr.worker.eventloop.tqmifc.HandlerStopOrder'>
*** msg: HandlerStopOrder(device_id='101187585uart')
*** has_device_id: True
*** device_id: '101187585uart'
** inner_run at /usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/worker/eventloop/__init__.py:205
*** msg: HandlerStopOrder(device_id='101187585uart')
*** self: <EventLoop(eventloop, started 140229448578816)>
*** msgs: <sai.moves.satella1.IterableReader object at 0x7f89b81b01d0>
** run at /usr/local/lib/python2.7/dist-packages/smok4svcr-4.5.18rc1-py2.7.egg/svcr/utils.py:46
*** self: <EventLoop(eventloop, started 140229448578816)>
** run_with_except_hook at /usr/local/lib/python2.7/dist-packages/smok4core-4.5.27-py2.7.egg/sai/basic/__init__.py:90
*** args: ()
*** kw: {}
*** run_old: <bound method EventLoop.run of <EventLoop(eventloop, started 140229448578816)>>
** __bootstrap_inner at /usr/lib/python2.7/threading.py:801
*** self: <EventLoop(eventloop, started 140229448578816)>
** __bootstrap at /usr/lib/python2.7/threading.py:774
*** self: <EventLoop(eventloop, started 140229448578816)>

```

**Comment by piotrmaslanka** [comment]
Timed out.
