### ISSUE TITLE
A battlefield report

### ISSUE THREAD

**Issue by piotrmaslanka** [smok-serwis/coolamqp#43]
```
Exception caught on 2019-12-30T12:58:26.199786:


Traceback (most recent call last):


  File "/usr/local/lib/python2.7/dist-packages/smok4core-4.5.27-py2.7.egg/sai/basic/__init__.py", line 90, in run_with_except_hook


    return run_old(*args, **kw)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/thread.py", line 43, in run


    self.listener.wait(timeout=1)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/epoll_listener.py", line 87, in wait


    sock.on_read()


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/socket.py", line 98, in on_read


    self.my_on_read(data)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py", line 64, in put


    while self._statemachine():


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py", line 156, in _statemachine


    self.on_frame(frame)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/connection.py", line 229, in on_frame


    watch_triggered = watch.is_triggered_by(frame)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/watches.py", line 141, in is_triggered_by


    self.callable(frame.payload)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 370, in on_setup


    self.on_setup(QueueBindOk())


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 379, in on_setup


    self.on_setup(BasicQosOk())  # pretend QoS went ok


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 388, in on_setup


    self.on_setup


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/channeler.py", line 197, in method_and_watch


    assert self.channel_id is not None


AssertionError




* Stack trace, innermost first


** method_and_watch at /usr/local/lib/python2.7/dist-packages/coolamqp/attaches/channeler.py:197


*** callable: <bound method Consumer.on_setup of <coolamqp.attaches.consumer.Consumer object at 0x7fad1c477210>>


*** self: <coolamqp.attaches.consumer.Consumer object at 0x7fad1c477210>


*** method_classes_to_watch: <class 'coolamqp.framing.definitions.BasicConsumeOk'>


*** method_payload: <coolamqp.framing.definitions.BasicConsume object at 0x7fad1cd6fc80>


** on_setup at /usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py:388


*** self: <coolamqp.attaches.consumer.Consumer object at 0x7fad1c477210>


*** payload: <coolamqp.framing.definitions.BasicQosOk object at 0x7fad1cd5e510>


** on_setup at /usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py:379


*** self: <coolamqp.attaches.consumer.Consumer object at 0x7fad1c477210>


*** payload: <coolamqp.framing.definitions.QueueBindOk object at 0x7fad1cd5e090>


** on_setup at /usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py:370


*** self: <coolamqp.attaches.consumer.Consumer object at 0x7fad1c477210>


*** payload: <coolamqp.framing.definitions.QueueDeclareOk object at 0x7fad1cd728e8>


** is_triggered_by at /usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/watches.py:143


*** frame: <coolamqp.framing.frames.AMQPMethodFrame object at 0x7fad1cd5e390>


*** self: <coolamqp.uplink.connection.watches.MethodWatch object at 0x7fad1cd95d90>


** on_frame at /usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/connection.py:229


*** alive_watches: [<coolamqp.uplink.connection.watches.MethodWatch object at 0x7fad1cd99250>]


*** frame: <coolamqp.framing.frames.AMQPMethodFrame object at 0x7fad1cd5e390>


*** watch_handled: False


*** watch: <coolamqp.uplink.connection.watches.MethodWatch object at 0x7fad1cd95d90>


*** watches: [<coolamqp.uplink.connection.watches.MethodWatch object at 0x7fad1cd99490>]


*** watch_triggered: False


*** self: <coolamqp.uplink.connection.connection.Connection object at 0x7fad1e1cbd50>


** _statemachine at /usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py:156


*** frame: <coolamqp.framing.frames.AMQPMethodFrame object at 0x7fad1cd5e390>


*** z: 206


*** payload: <memory at 0x7fad1c4922b0>


*** self: <coolamqp.uplink.connection.recv_framer.ReceivingFramer object at 0x7fad1e1cbd90>


** put at /usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py:64


*** self: <coolamqp.uplink.connection.recv_framer.ReceivingFramer object at 0x7fad1e1cbd90>


*** data: '\x01\xff\xb0\x00\x00\x00\x1e\x002\x00\x0b\x11sssp.27525121.out\x00\x00\x00\x00\x00\x00\x00\x00\xce'


** on_read at /usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/socket.py:100


*** self: <coolamqp.uplink.listener.epoll_listener.EpollSocket object at 0x7fad1e1cbe10>


*** data: '\x01\xff\xb0\x00\x00\x00\x1e\x002\x00\x0b\x11sssp.27525121.out\x00\x00\x00\x00\x00\x00\x00\x00\xce'


** wait at /usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/epoll_listener.py:102


*** mono: 3955.067566956


*** self: <coolamqp.uplink.listener.epoll_listener.EpollListener object at 0x7fad1e1cbd10>


*** sock: <coolamqp.uplink.listener.epoll_listener.EpollSocket object at 0x7fad1e1cbe10>


*** events: [(5, 1)]




5


*** timeout: 1


*** event: 1


** run at /usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/thread.py:43


*** self: <ListenerThread(coolamqp/ListenerThread, started daemon 140381510756096)>


** run_with_except_hook at /usr/local/lib/python2.7/dist-packages/smok4core-4.5.27-py2.7.egg/sai/basic/__init__.py:93


*** e: AssertionError()


*** args: ()


*** kw: {}


*** run_old: <bound method ListenerThread.run of <ListenerThread(coolamqp/ListenerThread, started daemon 140381510756096)>>


** __bootstrap_inner at /usr/lib/python2.7/threading.py:801


*** self: <ListenerThread(coolamqp/ListenerThread, started daemon 140381510756096)>


** __bootstrap at /usr/lib/python2.7/threading.py:774


*** self: <ListenerThread(coolamqp/ListenerThread, started daemon 140381510756096)>




*************************************************


Exception in thread coolamqp/ListenerThread:


Traceback (most recent call last):


  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner


    self.run()


  File "/usr/local/lib/python2.7/dist-packages/smok4core-4.5.27-py2.7.egg/sai/basic/__init__.py", line 90, in run_with_except_hook


    return run_old(*args, **kw)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/thread.py", line 43, in run


    self.listener.wait(timeout=1)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/epoll_listener.py", line 87, in wait


    sock.on_read()


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/listener/socket.py", line 98, in on_read


    self.my_on_read(data)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py", line 64, in put


    while self._statemachine():


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/recv_framer.py", line 156, in _statemachine


    self.on_frame(frame)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/connection.py", line 229, in on_frame


    watch_triggered = watch.is_triggered_by(frame)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/uplink/connection/watches.py", line 141, in is_triggered_by


    self.callable(frame.payload)


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 370, in on_setup


    self.on_setup(QueueBindOk())


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 379, in on_setup


    self.on_setup(BasicQosOk())  # pretend QoS went ok


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/consumer.py", line 388, in on_setup


    self.on_setup


  File "/usr/local/lib/python2.7/dist-packages/coolamqp/attaches/channeler.py", line 197, in method_and_watch


    assert self.channel_id is not None


AssertionError
```

**Comment by piotrmaslanka** [comment]
Timed out.
